<?php

/**
 * This is the model class for table "{{page_view}}".
 *
 * The followings are the available columns in table '{{page_view}}':
 * @property integer $tbl_page_view_id
 * @property integer $entity_id
 * @property string $entity_type
 * @property string $ip_address
 * @property string $visit_time
 */

 /**
 * PageView activerecord model class provides a mechanism to keep data and their
 * ...relevant business rules. A model instant represents a single database row.
 * ...
 * ...Usage:
 * ...   $view = PageView::model()
 * ...or
 * ...   $view = new PageView;
 * ...or
 * ...   $view = new PageView($scenario);
 *
 * @package   Components
 * @author    Pradesh <pradesh@datacraft.co.za>
 * @copyright 2014 florida.com
 * @package Components
 * @version 1.0
 */

class PageView extends CActiveRecord
{

    /**
     * Get database table name associated with the model.
     *
     * @param <none> <none>
     *
     * @return string the associated database table name
     * @access public
     */
	public function tableName()
	{
		return '{{page_view}}';
	}

    /**
     * Set rules for validation of model attributes. Each attribute is listed with its
     * ...associated rules. All attributes listed in the rules set forms a set of 'safe'
     * ...attributes that allow it to be used in massive assignment.
     *
     * @param <none> <none>
     *
     * @return array validation rules for model attributes.
     * @access public
     */
	public function rules()
	{

		return array(
			array('entity_id',                       'required'),
			array('entity_id',                       'numerical', 'integerOnly'=>true),
			array('entity_type, ip_address',         'length', 'max'=>255),

		    // Visit time is normally generated by beforeSave. There may be times we want to doctor times.
		    array('visit_time', 'safe'),

            // The following rule is used by search(). It only contains attributes that should be searched.
			array('tbl_page_view_id, entity_id, entity_type, ip_address, visit_time', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Set rules for the relation of this record model to other record models.
	 *
	 * @param <none> <none>
	 *
	 * @return array relational rules.
	 * @access public
	 */
	public function relations()
	{

		return array(
		);
	}

	/**
	 * Label set for attributes. Only required for attributes that appear on view/forms.
	 * ...
	 * Usage:
	 *    echo $form->label($model, $attribute)
	 *
	 * @param <none> <none>
	 *
	 * @return array customized attribute labels (name=>label)
	 * @access public
	 */
	public function attributeLabels()
	{
		return array(
			'tbl_page_view_id'       => 'Page View ID',
			'entity_id'              => 'Entity',
			'entity_type'            => 'Entity Type',
			'ip_address'             => 'Ip Address',
		    'visit_time'             => 'Visit Time',
		);
	}

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @param <none> <none>
     *
     * @return CActiveDataProvider the data provider that can return the models
     *         ...based on the search/filter conditions.
     * @access public
     */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('tbl_page_view_id',    $this->tbl_page_view_id);
		$criteria->compare('entity_id',           $this->entity_id);
		$criteria->compare('entity_type',         $this->entity_type,true);
		$criteria->compare('ip_address',          $this->ip_address,true);
		$criteria->compare('visit_time',          $this->visit_time,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     *
     * @param string $className active record class name.
     * @return PageView the static model class
     *
     * @access public
     */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * Runs just before the models save method is invoked. It provides a change to
	 * ...further prepare the data for saving. The CActiveRecord (parent class)
	 * ...beforeSave is called to process any raised events.
	 *
	 * @param <none> <none>
	 * @return boolean the decision to continue the save or not.
	 *
	 * @access public
	 */
	public function beforeSave()
	{

	    $this->visit_time = new CDbExpression('NOW()');

	    return parent::beforeSave();
	}
}
